apiVersion: v1
kind: ConfigMap
metadata:
  name: getappshots-config
  namespace: getappshots
data:
  # Web
  NODE_ENV: "production"
  # API
  API_PORT: "8000"
  # Redis (service name)
  REDIS_URL: "redis://redis.getappshots.svc.cluster.local:6379/0"

